lotatc_inst.options =  {
    -- Generated by LotAtc Configurator
    -- Version :2.2.1
    -- Date    :11.05.2021 14:46:05
    port = 10326,
    virtual_awacs_name = "",
    chat_filter = {"^-.*"},
    dedicated_mode = true,
    allowed_users_file = "",
}
