lotatc_inst.options =  {
    -- Generated by LotAtc Configurator
    -- Version :2.2.1
    -- Date    :11.05.2021 14:47:59
    port = 10329,
    chat_filter = {"^-.*"},
    dedicated_mode = true,
    allowed_users_file = "",
    use_admin_commands = false,
    dump_json_stats = false,
    export_log = false,
    export_tacview = false,
    use_jsonserver = true,
}
