lotatc_inst.options =  {
    -- Generated by LotAtc Configurator
    -- Version :2.2.1
    -- Date    :12.05.2021 21:07:20
    port = 10324,
    virtual_awacs_name = "",
    chat_filter = {"^-.*"},
    dedicated_mode = true,
    dedicated_profile = "advanced-realistic_copy.lua",
}
