lotatc_inst.options =  {
    -- Generated by LotAtc Configurator
    -- Version :2.2.1
    -- Date    :11.05.2021 14:45:18
    port = 10325,
    chat_filter = {"^-.*"},
    dedicated_mode = true,
    allowed_users_file = "",
}
